name: basic-checkout
on:
  push
jobs:
  basic-checkout:
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
    - uses: actions/checkout@v2
    - name: show files
      run: ls -lisah