name: build-with-ubuntu-latest-no-docker
on:
  push
jobs:
  build-with-ubuntu-latest:
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:
    
    # Setup Java environment in order to build the Android app.
    - uses: actions/checkout@v1
    - shell: bash
      env:
        SECRETS_JSON_FILE: ${{ secrets.SECRETS_JSON_FILE }}
        run: |
          echo "$SECRETS_JSON_FILE" > secrets.json

    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    
    # Setup the flutter environment.
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.17.5'
    
    # Get flutter dependencies.
    - run: flutter pub get
    
    # Check for any formatting issues in the code. | we don´t want this as we have 120 chars line length
    #- run: flutter format --set-exit-if-changed .
    
    # Statically analyze the Dart code for any errors.
    - run: flutter analyze .
    
    # Run widget tests for our flutter project.
    - run: flutter test
    
    # Build apk.
    - run: flutter build apk --debug
    
    # Upload generated apk to the artifacts.
    - uses: actions/upload-artifact@v1
      with:
        name: release debug apk
        path: build/app/outputs/apk/debug/app-debug.apk
